site_name: HAPPYLAND 官方文档
site_author: HAPPYLAND Dev Group

repo_url: https://github.com/HAPPYLAND-Dev/assiah-docs

theme:
  name: material
  language: zh
  highlightjs: true
  palette:
    primary: teal
    accent: teal
  font:
    text: Noto Sans SC
    code: Noto Sans Mono

extra:
  favicon: extra/favicon.png

markdown_extensions:
  - smarty: {}
  - toc:
      permalink: True
  - sane_lists: {}
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.superfences

plugins:
  - search

nav:
  - AssiashLand:
      - 主页: assiash/index.md
      - 基础: assiash/info.md
      - 岛屿玩法:
          - 前言: assiash/island/index.md
          - 精灵: assiash/island/allay.md
          - 任务: assiash/island/quest.md
          - 人偶: assiash/island/puppet.md
          - 指令: assiash/island/command.md
          - 子区: assiash/island/region.md
      - 世界:
          - 世界组成: assiash/world/index.md
          - 岛屿类型: assiash/world/island.md
      - 禁忌:
          - 客户端使用: assiash/banned/client.md
          - 处罚机制: assiash/banned/temp.md
      # - 经济: assiash/eco/index.md
      # - 补丁更新: assiash/patches/index.md
  # - YetzirahLand:
  #     - 主页: yetzirah/index.md
  #     - 玩法简介: yetzirah/starter/introduction.md
  #     - 新手建议: yetzirah/starter/suggestion.md
  - 听歌: simple.md
  - 胡说八道:
    - 发发牢骚: baga/fku.md
