site_name: HAPPYLAND 官方文档
site_author: HAPPYLAND Dev Group

repo_url: https://github.com/HAPPYLAND-Dev/assiah-docs

theme:
  name: material
  language: zh
  highlightjs: true
  palette:
    primary: teal
    accent: teal
  font:
    text: Noto Sans SC
    code: Noto Sans Mono

markdown_extensions:
  - smarty: {}
  - toc:
      permalink: True
  - sane_lists: {}
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.superfences

plugins:
  - search

nav:
  - AssiashLand:
      - 主页: assiash/index.md
      - 科技:
          - 前言: assiash/tech/index.md
          - 概要: assiash/tech/dumortierite.md
          - 机器产物表: assiash/tech/recipes.md
      - 世界:
          - 世界组成: assiash/world/index.md
      - 经济: assiash/eco/index.md
      - 岛屿玩法:
          - 前言: assiash/island/index.md
          - 精灵: assiash/island/allay.md
          - 任务: assiash/island/quest.md
          - 人偶: assiash/island/puppet.md
  - YetzirahLand:
      - 主页: yetzirah/index.md
      - 玩法简介: yetzirah/starter/introduction.md
      - 新手建议: yetzirah/starter/suggestion.md
