site_name: AssiahLand 官方文档
site_author: HAPPYLAND Dev Group

repo_url: https://github.com/HAPPYLAND-Dev/assiah-docs

theme: 
   name: material
   language: zh
   highlightjs: true

markdown_extensions:
   - smarty: {}
   - toc:
       permalink: True
   - sane_lists: {}
   - pymdownx.highlight:
       auto_title: true
       linenums: true
   - pymdownx.superfences
   
plugins: 
   - search

nav:
   - 主页: index.md
   - 科技:
      - 前言: tech/index.md
      - 概要: tech/dumortierite.md
      - 机器产物表: tech/recipes.md
   - 世界:
      - 世界组成: world/index.md